// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// pnpm add -D prisma dotenv
import "dotenv/config"; // Import the dotenv package to load environment variables from a .env file
import { defineConfig } from "prisma/config"; // Import the defineConfig function from the Prisma config module

export default defineConfig({
  schema: "prisma/schema.prisma", // Path to your Prisma schema file
  migrations: {
    path: "prisma/migrations", // Path to your migrations directory
  },
  datasource: {
    url: process.env["DATABASE_URL"], // Use the DATABASE_URL environment variable for the database connection
  },
});
